apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rtd-cache-pvc
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 5Ti