apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rtd-cache-pvc-mini
spec:
  storageClassName: rook-cephfs
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 10Ti