apiVersion: batch/v1
kind: Job
metadata:
  name: diffsvgf-rtdenoise-training
  labels:
    name: diffsvgf-rtdenoise-training
spec:
  completions: 1
  parallelism: 1
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: diffsvgf-rtdenoise-training
        image: saadam1n/rtdenoise:latest
        command: ["/bin/sh", "-c", "RTDENOISE_DATASET_PATH=/mnt/rtdenoise_dataset_tar_filtered_mini/ RTDENOISE_OUTPUT_PATH=/mnt/rtdenoise_out/ RTDENOISE_DOWNLOAD_CACHE=/mnt/download_cache/ python3 -u scripts/sample_train.py"]
        resources:
          requests:
            memory: "48Gi"
            cpu: "20"
            nvidia.com/gpu: "1" 
          limits:
            memory: "48Gi"
            cpu: "20"
            nvidia.com/gpu: "1" 
        volumeMounts:
        - mountPath: /mnt/rtdenoise_dataset_tar_filtered_mini/
          name: rtdenoise-dataset-tar-filtered-mini
        - mountPath: /mnt/rtdenoise_out/
          name: rtd-cache-pvc-mini
        - mountPath: /dev/shm
          name: dshm
        - mountPath: /mnt/download_cache
          name: download-cache
      volumes:
          - name: rtdenoise-dataset-tar-filtered-mini
            persistentVolumeClaim:
              claimName: rtdenoise-dataset-tar-filtered-mini
          - name: rtd-cache-pvc-mini
            persistentVolumeClaim:
              claimName: rtd-cache-pvc-mini
          - name: dshm
            emptyDir:
              medium: Memory
              sizeLimit: 16Gi
          - name: download-cache
            emptyDir:
              medium: Memory
              sizeLimit: 16Gi
