apiVersion: batch/v1
kind: Job
metadata:
  name: diffsvgf-rtdenoise-training
  labels:
    name: diffsvgf-rtdenoise-training
spec:
  completions: 1
  parallelism: 1
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: diffsvgf-rtdenoise-training
        image: saadam1n/rtdenoise:latest
        command: ["/bin/sh", "-c", "RTDENOISE_DATASET_PATH=/mnt/rtdenoise_dataset_tar_filtered/ RTDENOISE_OUTPUT_PATH=/mnt/rtdenoise_out/ RTDENOISE_DOWNLOAD_CACHE=/mnt/download_cache/ python3 -u scripts/sample_train.py"]
        resources:
          requests:
            memory: "192Gi"
            cpu: "360"
          limits:
            memory: "192Gi"
            cpu: "360"
        volumeMounts:
        - mountPath: /mnt/rtdenoise_dataset_tar_filtered/
          name: rtdenoise-dataset-tar-filtered
        - mountPath: /mnt/rtdenoise_out/
          name: rtd-cache-pvc
        - mountPath: /dev/shm
          name: dshm
        - mountPath: /mnt/download_cache
          name: download-cache
      volumes:
          - name: rtdenoise-dataset-tar-filtered
            persistentVolumeClaim:
              claimName: rtdenoise-dataset-tar-filtered
          - name: rtd-cache-pvc
            persistentVolumeClaim:
              claimName: rtd-cache-pvc
          - name: dshm
            emptyDir:
              medium: Memory
              sizeLimit: 64Gi
          - name: download-cache
            emptyDir:
              medium: Memory
              sizeLimit: 48Gi
