apiVersion: v1
kind: Pod
metadata:
  name: rtdenoise-upload-pod
spec:
  containers:
  - name: rtdenoise-upload-pod
    image: busybox
    command: [ "sleep", "7200" ]  # Keeps the pod running for a while
    resources:
      requests:
        memory: "16Gi"
        cpu: "8"
      limits:
        memory: "32Gi"
        cpu: "8"
    volumeMounts:
    - mountPath: /mnt/datasets/
      name: trainingdata
  volumes:
  - name: trainingdata
    persistentVolumeClaim:
      claimName: rtd-pvc